Repository opengisch/QField, pull requests merged in 2020-07, with the labels that each got.

#1115 Switch to android libz
  CMakeLists.txt
  sdk.conf
Labels: backport release-1_6

#1047 Fix for double validators
  src/qml/editorwidgets/Range.qml
  src/qml/editorwidgets/TextEdit.qml
Labels: backport release-1_6

#1118 Fix Feature Form problems depending on isEnabled and AttributeAllowEdit
  src/core/attributeformmodelbase.cpp
  src/qml/FeatureForm.qml
  src/qml/editorwidgets/ExternalResource.qml
  src/qml/editorwidgets/RelationEditor.qml
  src/qml/editorwidgets/TextEdit.qml
  src/qml/editorwidgets/ValueRelation.qml
Labels: backport release-1_6

#1129 Fix #1119 Button to edit geometry no longer available
  src/qml/NavigationBar.qml
Labels: backport release-1_6

#1146 Increase the touch-only hoverhandler timer to avoid location marker jumping around
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_6

#1147 Fix snapping on HiDPI screens
  src/core/snappingutils.cpp
Labels: BUG, backport release-1_6

#1154 Polish ValueRelationWidget
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/ValueRelation.qml
Labels: backport release-1_6

#1142 Reduce map identify radius
  src/qml/qgismobileapp.qml
Labels: backport release-1_6

#1168 Silence more warnings
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_6

#1167 Layer properties popup fixes and improvements
  src/qml/LayerTreeItemProperties.qml
Labels: BUG

#1166 Set vector layer to null to address QML warning
  src/qml/Legend.qml
Labels: BUG, backport release-1_6

#1174 Fix DCIM folder not showing up
  android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
  android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
Labels: backport release-1_6
