Repository opengisch/QField, pull requests merged in 2020-12, with the labels that each got.

#1446 use target_include_directories rahter than include_directories
  src/app/CMakeLists.txt
  src/core/CMakeLists.txt
  test/CMakeLists.txt
Labels: Squash!

#1490 Fix not null constraint checks where default values are available
  src/core/attributeformmodelbase.cpp
Labels: backport release-1_7

#1516 Release Drafter
  .github/release_drafter.yml
  .github/workflows/release_drafter.yml
Labels: chore, minor

#1518 Fix capitalization
  src/qml/LayerTreeItemProperties.qml
Labels: UX/UI, patch

#1525 Improvement to ordering, location, and width of main menu and GPS menu
  src/qml/qgismobileapp.qml
Labels: UX/UI, minor

#1529 When toggling digitizing on, insure an editable layer is selected
  src/qml/qgismobileapp.qml
Labels: UX/UI, backport release-1_8, patch

#1524 Fix search bar x clear action on virtual keyboards, increase hit area
  src/qml/LocatorItem.qml
Labels: BUG, backport release-1_8

#1526 Merry holiday and happy rippling
  src/qml/imports/Theme/QfToolButton.qml
Labels: backport release-1_8, minor

#1528 When applying a digitized geometry, insure invalid intersections are removed
  src/core/featuremodel.cpp
Labels: backport release-1_8, minor

#1519 Add a zoom in/out button on the main screen
  images/images.qrc
  images/themes/qfield/hdpi/ic_add_vertex_white_24dp.png
  images/themes/qfield/hdpi/ic_remove_vertex_white_24dp.png
  images/themes/qfield/mdpi/ic_add_vertex_white_24dp.png
  images/themes/qfield/mdpi/ic_remove_vertex_white_24dp.png
  images/themes/qfield/xhdpi/ic_add_vertex_white_24dp.png
  images/themes/qfield/xhdpi/ic_remove_vertex_white_24dp.png
  images/themes/qfield/xxhdpi/ic_add_vertex_white_24dp.png
  images/themes/qfield/xxhdpi/ic_remove_vertex_white_24dp.png
  images/themes/qfield/xxxhdpi/ic_add_vertex_white_24dp.png
  images/themes/qfield/xxxhdpi/ic_remove_vertex_white_24dp.png
  src/qml/DigitizingToolbar.qml
  src/qml/MapCanvas.qml
  src/qml/geometry_editors/VertexEditorToolbar.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, minor

#1551 Show commit sha in the about dialog
  CMakeLists.txt
  scripts/ci/build.sh
  scripts/deploy.sh
  scripts/docker-build.sh
  scripts/version_number.sh
  src/core/changelogcontents.cpp
  src/core/qgismobileapp.cpp
  src/qml/About.qml
  src/qml/Changelog.qml
  src/qml/qgismobileapp.qml
  test/test_version_number.sh
Labels: ENHANCEMENT, minor
