Repository opengisch/QField, pull requests merged in 2020-11, with the labels that each got.

#1389 Fix QField _always_ ignoring project transformation settings
  src/qgsquick/qgsquickmapsettings.cpp
Labels: BUG, backport release-1_7

#1269 targetSdkVersion 29 upgrade and `getExternalStorageDirectory()`
  .github/workflows/continuous_integration.yml
  cmake/AndroidManifest.xml.in
  scripts/ci/build.sh
Labels: backport release-1_7

#1390 Move QtWebView::initalize so it happens _before_ QgsApplication app on android
  src/app/main.cpp
  src/qml/FeatureForm.qml
Labels: backport release-1_7

#1380 Allow users to define postgresql services in a pg_service.conf on their devices
  android/src/ch/opengis/qfield/QFieldActivity.java
  src/core/androidplatformutilities.cpp
  src/core/androidplatformutilities.h
  src/core/platformutilities.cpp
  src/core/platformutilities.h
  src/core/qgismobileapp.cpp
Labels: needs documentation

#1404 Fix text clipped in the missing layer(s) panel
  src/qml/BadLayerItem.qml
Labels: BUG, backport release-1_7

#1403 Fields that aren't visible should always return valid constraints
  src/core/attributeformmodelbase.cpp
Labels: BUG, backport release-1_7

#1402 Workflow improvements
  .github/workflows/continuous_integration.yml
  .github/workflows/translations.yml
  scripts/ci/upload_artifacts.sh
  scripts/upload-artifacts.sh
Labels: backport release-1_7

#1431 Respect feature defaults when creating a new feature
  src/core/featuremodel.cpp
Labels: backport release-1_7
