Repository opengisch/QField, pull requests merged in 2020-03, with the labels that each got.

#862 Fix storing new variables
  src/qml/QFieldSettings.qml
Labels: backport release-1_4

#854 Extract Embedded Feature Form
  src/qml/EmbeddedFeatureForm.qml
  src/qml/editorwidgets/RelationEditor.qml
  src/qml/qml.qrc
Labels: Ready For Review

#845 use modified icons for the different apps (main, dev/beta and PR)
  android/AndroidManifest.xml
  android/res/drawable-hdpi/icon.png
  android/res/drawable-hdpi/qfield_logo.png
  android/res/drawable-hdpi/qfield_logo_beta.png
  android/res/drawable-hdpi/qfield_logo_pr.png
  android/res/drawable-mdpi/icon.png
  android/res/drawable-mdpi/qfield_logo.png
  android/res/drawable-mdpi/qfield_logo_beta.png
  android/res/drawable-mdpi/qfield_logo_pr.png
  android/res/drawable-xhdpi/icon.png
  android/res/drawable-xhdpi/qfield_logo.png
  android/res/drawable-xhdpi/qfield_logo_beta.png
  android/res/drawable-xhdpi/qfield_logo_pr.png
  android/res/drawable-xxhdpi/icon.png
  android/res/drawable-xxhdpi/qfield_logo.png
  android/res/drawable-xxhdpi/qfield_logo_beta.png
  android/res/drawable-xxhdpi/qfield_logo_pr.png
  android/res/drawable-xxxhdpi/icon.png
  android/res/drawable-xxxhdpi/qfield_logo.png
  android/res/drawable-xxxhdpi/qfield_logo_beta.png
  android/res/drawable-xxxhdpi/qfield_logo_pr.png
  android/res/drawable/icon.png
  android/res/layout/unpacking_dialog.xml
  android/src/ch/opengis/qfield/QFieldProjectActivity.java
  images/icons/qfield-testlogo.svg
  images/icons/qfield_logo.svg
  images/icons/qfield_logo_beta.svg
  images/icons/qfield_logo_pr.svg
  images/images.qrc
  scripts/ci/travis_build.sh
  scripts/create-images.sh
  scripts/docker-build.sh
  src/qml/WelcomeScreen.qml
Labels: Squash!

#855 Track Lines and Polygons reloaded
  images/images.qrc
  images/themes/qfield/hdpi/ic_directions_walk_black_24dp.png
  images/themes/qfield/mdpi/ic_directions_walk_black_24dp.png
  images/themes/qfield/nodpi/ic_directions_walk_black_24dp.png
  images/themes/qfield/xhdpi/ic_directions_walk_black_24dp.png
  images/themes/qfield/xxhdpi/ic_directions_walk_black_24dp.png
  images/themes/qfield/xxxhdpi/ic_directions_walk_black_24dp.png
  src/core/CMakeLists.txt
  src/core/core.pro
  src/core/layertreemapcanvasbridge.cpp
  src/core/layertreemapcanvasbridge.h
  src/core/layertreemodel.cpp
  src/core/layertreemodel.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/core/rubberbandmodel.cpp
  src/core/rubberbandmodel.h
  src/core/tracker.cpp
  src/core/tracker.h
  src/core/trackingmodel.cpp
  src/core/trackingmodel.h
  src/qml/FeatureForm.qml
  src/qml/FeatureListForm.qml
  src/qml/LayerTreeItemProperties.qml
  src/qml/Legend.qml
  src/qml/Tracking.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
  src/qml/ui/LayerTreeItemProperties.qml
Labels: Ready For Review

#878 Fix positioning after activation
  src/core/androidplatformutilities.cpp
  src/qml/qgismobileapp.qml
Labels: BUG, Ready For Review, backport release-1_4

#880 Message for the status while getting the position
  src/qml/qgismobileapp.qml
Labels: backport release-1_4

#857 💍 Fill ring map tool
  images/images.qrc
  images/themes/qfield/hdpi/picture_in_picture.png
  images/themes/qfield/mdpi/picture_in_picture.png
  images/themes/qfield/nodpi/picture_in_picture.svg
  images/themes/qfield/xhdpi/picture_in_picture.png
  images/themes/qfield/xxhdpi/picture_in_picture.png
  images/themes/qfield/xxxhdpi/picture_in_picture.png
  sdk.conf
  src/app/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/core.pro
  src/core/qgismobileapp.cpp
  src/core/rubberbandmodel.cpp
  src/core/rubberbandmodel.h
  src/core/utils/featureutils.cpp
  src/core/utils/featureutils.h
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/core/utils/geometryutils.cpp
  src/core/utils/geometryutils.h
  src/qml/EmbeddedFeatureForm.qml
  src/qml/FeatureForm.qml
  src/qml/QuestionDialog.qml
  src/qml/geometry_editors/FillRingToolBar.qml
  src/qml/geometry_editors/GeometryEditorsToolbar.qml
  src/qml/geometry_editors/SplitFeatureToolbar.qml
  src/qml/geometry_editors/VertexEditorToolbar.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: Squash!

#790 Use expression configured in QFieldSync for picturenames
  android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
  android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
  android/src/ch/opengis/qfield/QFieldOpenExternallyActivity.java
  src/core/CMakeLists.txt
  src/core/androidpicturesource.cpp
  src/core/androidplatformutilities.cpp
  src/core/androidplatformutilities.h
  src/core/core.pro
  src/core/expressionevaluator.cpp
  src/core/expressionevaluator.h
  src/core/platformutilities.cpp
  src/core/platformutilities.h
  src/core/qgismobileapp.cpp
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/qml/FeatureForm.qml
  src/qml/editorwidgets/ExternalResource.qml
Labels: Ready For Review

#882 Position activated in the PositioningSettings and improvement
  src/qml/PositioningSettings.qml
  src/qml/PositioningSettingsPopup.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: Ready For Review

#890 Do not show toasts on welcome screen
  src/qml/qgismobileapp.qml
Labels: Ready For Review

#889 Fix that it tries to open a folder on image click without file
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
Labels: Ready For Review

#879 Fix positioning after activation (#878)
  src/core/androidplatformutilities.cpp
  src/qml/qgismobileapp.qml
Labels: Ready For Review

#902 Handle the config changes by the activity
  android/AndroidManifest.xml
Labels: backport release-1_5

#907 Use standard method for KeepScreenOn flag
  src/core/androidplatformutilities.cpp
Labels: backport release-1_5

#906 Not Null and Unique Constraints
  resources/demo_projects/advanced_bee_farming.qgs
  resources/demo_projects/simple_bee_farming.qgs
  src/core/attributeformmodelbase.cpp
  src/qml/FeatureForm.qml
Labels: backport release-1_5

#881 message what's happening on change of the gps icons (#880)
  src/qml/qgismobileapp.qml
Labels: Ready For Review

#910 Fix constraint description height
  src/qml/FeatureForm.qml
Labels: backport release-1_5

#915 Fix center GPS over menu
  src/qml/qgismobileapp.qml
Labels: backport release-1_5
