Repository opengisch/QField, pull requests merged in 2020-02, with the labels that each got.

#798 Camera: Only display buttons on edit mode
  src/qml/editorwidgets/ExternalResource.qml
Labels: Ready For Review

#797 Enable native camera on default
  src/qml/QFieldSettings.qml
Labels: Ready For Review

#802 create image dir
  android/src/ch/opengis/qfield/QFieldCameraPictureActivity.java
  android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
Labels: Ready For Review

#809 Toaster improvements
  src/qml/qgismobileapp.qml
Labels: Ready For Review

#817 Do not store empty image path on cancel
  src/core/androidpicturesource.cpp
  src/qml/editorwidgets/ExternalResource.qml
Labels: Ready For Review

#819 adapt deploy scripts to stable/master branches
  scripts/ci/travis_build.sh
  scripts/deploy.sh
  src/qml/About.qml
Labels: backport stable

#822 run Travis on stable/master
  .travis.yml
Labels: backport master

#803 new setting for native cam
  src/qml/QFieldSettings.qml
  src/qml/editorwidgets/ExternalResource.qml
Labels: Ready For Review

#827 adapt script to support release branches
  .travis.yml
  scripts/deploy.sh
Labels: backport release-1_4

#849 Remove open image option
  src/qml/editorwidgets/ExternalResource.qml
Labels: backport release-1_4

#780 View Images in Feature Form
  android/AndroidManifest.xml
  android/res/xml/file_paths.xml
  android/src/ch/opengis/qfield/QFieldOpenExternallyActivity.java
  src/core/androidplatformutilities.cpp
  src/core/androidplatformutilities.h
  src/core/platformutilities.cpp
  src/core/platformutilities.h
  src/core/qgismobileapp.cpp
  src/qml/editorwidgets/ExternalResource.qml
Labels: Ready For Review
