Repository opengisch/QField, pull requests merged in 2021-06, with the labels that each got.

#1953 Improve embedded forms feedback
  src/qml/FeatureForm.qml
  src/qml/editorwidgets/DateTime.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, backport release-1_9, patch

#1963 Allow users (via the welcome screen) to specify the default project to use when opening individual datasets
  src/core/qgismobileapp.cpp
  src/qml/WelcomeScreen.qml
Labels: needs documentation

#1966 Support loading of QGIS projects saved inside geopackage files
  src/core/qgismobileapp.cpp
Labels: ENHANCEMENT

#1980 Add a description why bluetooth is required
  ios/Info.plist.in
Labels: backport release-2_0

#1984 Add version for ios
  src/app/CMakeLists.txt
Labels: backport release-2_0

#1986 Allow text wrapping for value relation widget
  src/qml/editorwidgets/ValueRelation.qml
Labels: backport release-2_0

#1979 Until we support those, prevent text editing of JSON / list fields
  src/qml/editorwidgets/TextEdit.qml
Labels: backport release-2_0

#1987 Important fix to geometry editor handling of vertex digitizing
  src/qml/geometry_editors/FillRingToolBar.qml
  src/qml/geometry_editors/ReshapeToolBar.qml
  src/qml/geometry_editors/SplitFeatureToolbar.qml
  src/qml/qgismobileapp.qml
Labels: backport release-1_9, backport release-2_0

#1971 Digitizing logger feature
  src/core/CMakeLists.txt
  src/core/digitizinglogger.cpp
  src/core/digitizinglogger.h
  src/core/featuremodel.h
  src/core/gnsspositioninformation.cpp
  src/core/gnsspositioninformation.h
  src/core/qgismobileapp.cpp
  src/core/snappingresult.cpp
  src/core/snappingresult.h
  src/core/vertexmodel.cpp
  src/qml/CoordinateLocator.qml
  src/qml/DigitizingToolbar.qml
  src/qml/EmbeddedFeatureForm.qml
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/geometry_editors/FillRingToolBar.qml
  src/qml/geometry_editors/ReshapeToolBar.qml
  src/qml/geometry_editors/SplitFeatureToolbar.qml
  src/qml/geometry_editors/VertexEditorToolbar.qml
  src/qml/qgismobileapp.qml
  test/CMakeLists.txt
  test/test_digitizinglogger.cpp
Labels: needs documentation

#1998 Fix the changelog listening to QNetworkAccessManager
  src/core/changelogcontents.cpp
Labels: backport release-2_0

#1996 Fix reshape tool handling of geometry operation return values
  src/core/utils/geometryutils.cpp
Labels: backport release-2_0

#2005 Identify NMEA position information source
  src/core/bluetoothreceiver.cpp
Labels: backport release-2_0

#2008 Fix text edit widget editable's logic
  src/qml/editorwidgets/TextEdit.qml
Labels: backport release-2_0
