Repository opengisch/QField, pull requests merged in 2021-05, with the labels that each got.

#1875 Fix missing @snapping_results variable content (fixes #1871)
  src/qml/EmbeddedFeatureForm.qml
  src/qml/OverlayFeatureFormDrawer.qml
Labels: backport release-1_9

#1888 Fix ListView going broken when resetting feature form
  src/qml/FeatureForm.qml
Labels: BUG, backport release-1_9

#1890 [backport release-1_9] Fix ListView going broken when resetting feature form
  src/qml/FeatureForm.qml
Labels: BUG

#1889 Improvements to the checkbox editor widget
  src/qml/editorwidgets/CheckBox.qml
  src/qml/imports/Theme/QfSwitch.qml
Labels: BUG, backport release-1_9

#1893 Relation combobox fixes and improvements
  src/core/featurechecklistmodel.cpp
  src/core/qgismobileapp.cpp
  src/qml/RelationCombobox.qml
Labels: BUG, backport release-1_9

#1891 Focus improvements all around
  src/qml/FeatureListForm.qml
  src/qml/NavigationBar.qml
  src/qml/imports/Theme/QfToolButton.qml
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_9

#1909 When exiting the multi selection mode via the back key, clear selection
  src/qml/FeatureListForm.qml
Labels: BUG, backport release-1_9

#1908 Always show the iOS and cancel/delete button in the add feature form
  src/qml/FeatureForm.qml
  src/qml/NavigationBar.qml
  src/qml/Tracking.qml
Labels: BUG, backport release-1_9

#1916 Fix using cloud information variables in all feature forms (@cloud_username etc)
  src/qml/EmbeddedFeatureForm.qml
  src/qml/FeatureListForm.qml
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/Tracking.qml
  src/qml/qgismobileapp.qml
Labels: BUG, patch

#1907 QField OAuth2 support
  CMakeLists.txt
  android/src/ch/opengis/qfield/QFieldActivity.java
  cmake/AndroidManifest.xml.in
  cmake/FindQCA.cmake
  cmake/FindQtKeychain.cmake
  sdk.conf
  src/app/main.cpp
  src/core/CMakeLists.txt
  src/core/platformutilities.cpp
  src/core/qfieldappauthrequesthandler.cpp
  src/core/qfieldappauthrequesthandler.h
  src/core/qgismobileapp.cpp
  src/core/utils/layerutils.cpp
  src/qml/BrowserPanel.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
  vcpkg/overlay/qgis/portfile.cmake
Labels: ENHANCEMENT

#1932 Allow 2-vertex line and 3-vertex polygons
  src/qml/DigitizingToolbar.qml
Labels: backport release-1_9

#1935 Fix feature addition
  src/qml/FeatureForm.qml
Labels: BUG, backport release-1_9

#1930 Fix snapping to segment
  src/core/snappingutils.cpp
Labels: backport release-1_9

#1937 Fix double feature creation when adding points in fast editing mode
  src/qml/FeatureForm.qml
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_9

#1943 One more legend corner scenario: insertion of rows with pre-existing children
  src/core/layertreemodel.cpp
Labels: BUG, backport release-1_9

#1945 Fix legend showing wrong symbol for layer sub items with same name
  src/core/layertreemodel.cpp
  src/core/legendimageprovider.cpp
Labels: BUG, backport release-1_9
