Repository opengisch/QField, pull requests merged in 2021-12, with the labels that each got.

#2349 Fix errors happened in the previous project being still visible if when a a new project is opened
  src/qml/QFieldCloudPopup.qml
Labels: BUG, patch

#2317 Added layer CRS authid and layer name to the delta
  src/core/deltafilewrapper.cpp
  src/core/deltafilewrapper.h
  test/test_deltafilewrapper.cpp
Labels: ENHANCEMENT, qfieldcloud, patch

#2351 Remove cloud project from the recent projects when removed from the cloud projects list
  src/core/qfieldcloudprojectsmodel.cpp
  src/qml/QFieldCloudPopup.qml
  src/qml/QFieldCloudScreen.qml
Labels: BUG, patch

#2356 Remove last leftovers from the black buttons in the header bar in QField forms
  src/qml/FeatureForm.qml
Labels: ENHANCEMENT

#2355 Bookmark basics
  images/images.qrc
  images/themes/qfield/nodpi/ic_place_white_24dp.svg
  src/core/CMakeLists.txt
  src/core/bookmarkmodel.cpp
  src/core/bookmarkmodel.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/qml/BookmarkHighlight.qml
  src/qml/BookmarkRenderer.qml
  src/qml/GeometryRenderer.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: needs documentation
