Repository opengisch/QField, pull requests merged in 2021-01, with the labels that each got.

#1527 Brand new reshape tool
  images/images.qrc
  images/themes/qfield/hdpi/ic_reshape_tool_white_24dp.png
  images/themes/qfield/mdpi/ic_reshape_tool_white_24dp.png
  images/themes/qfield/nodpi/ic_reshape_tool_white_24dp.svg
  images/themes/qfield/nodpi/ic_split_tool_white_24dp.svg
  images/themes/qfield/xhdpi/ic_reshape_tool_white_24dp.png
  images/themes/qfield/xxhdpi/ic_reshape_tool_white_24dp.png
  images/themes/qfield/xxxhdpi/ic_reshape_tool_white_24dp.png
  src/core/featuremodel.cpp
  src/core/rubberbandmodel.cpp
  src/core/utils/geometryutils.cpp
  src/core/utils/geometryutils.h
  src/qml/MapCanvas.qml
  src/qml/geometry_editors/GeometryEditorsToolbar.qml
  src/qml/geometry_editors/ReshapeToolBar.qml
  src/qml/geometry_editors/SplitFeatureToolbar.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT, major

#1549 Use supportsEditing flag to determine whether to show the edit button
  sdk.conf
  src/qml/NavigationBar.qml
Labels: UX/UI, minor

#1560 Fix position information view's antenna height
  src/qml/PositionInformationView.qml
Labels: BUG, backport release-1_8

#1562 Let QML trigger the connection
  src/core/bluetoothreceiver.cpp
  src/qml/TransformedPositionSource.qml
Labels: BUG, backport release-1_8

#1556 Positioning accuracy indicator and digitizing accuracy requirement
  src/qml/CoordinateLocator.qml
  src/qml/DigitizingToolbar.qml
  src/qml/PositioningSettings.qml
  src/qml/QFieldSettings.qml
  src/qml/imports/Theme/Theme.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, backport release-1_8, minor

#1572 Proxy alias text QfTextField
  src/qml/imports/Theme/QfTextField.qml
Labels: backport release-1_8

#1539 Support for colors in attribute forms 🎨
  src/core/attributeformmodel.h
  src/core/attributeformmodelbase.cpp
  src/core/attributeformmodelbase.h
  src/qml/FeatureForm.qml
Labels: ENHANCEMENT, minor

#1582 Avoid start tracking without definitions
  src/qml/Tracking.qml
Labels: backport release-1_8

#1586 Backport merges
  .github/workflows/backport.yml
  scripts/prepare-commit.sh
Labels: backport release-1_8

#1585 Internal positioning fixes and variable name adjustments
  src/core/bluetoothreceiver.cpp
  src/core/bluetoothreceiver.h
  src/core/expressioncontextutils.cpp
  src/qml/TransformedPositionSource.qml
Labels: backport release-1_8

#1584 Add system loader dialog
  src/core/CMakeLists.txt
  src/core/androidplatformutilities.cpp
  src/core/feedback.cpp
  src/core/feedback.h
  src/core/qgismobileapp.cpp
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/qml/SystemLoader.qml
  src/qml/qml.qrc
Labels: backport release-1_8

#1583 Revert to Qt 5.14.2
  .github/workflows/code_layout.yml
  sdk.conf
Labels: backport release-1_8

#1484 Fix the blank screen on resume issue while greatly simplifying manifest & QFieldActivity java class
  android/src/ch/opengis/qfield/QFieldActivity.java
  cmake/AndroidManifest.xml.in
  src/core/qgismobileapp.cpp
Labels: BUG, backport release-1_8

#1590 Add position_3d_accuracy for 3DRMS
  src/core/expressioncontextutils.cpp
  src/core/gnsspositioninformation.cpp
  src/core/gnsspositioninformation.h
Labels: minor

#1592 Request external storage permission early
  android/src/ch/opengis/qfield/QFieldActivity.java
Labels: backport release-1_8

#1594 Nice speed boost for complex vector layers by enabling rendering optimization
  src/core/qgsquick/qgsquickmapcanvasmap.cpp
Labels: backport release-1_8

#1589 Add layer resolver
  src/core/CMakeLists.txt
  src/core/layerresolver.cpp
  src/core/layerresolver.h
  src/core/qgismobileapp.cpp
  src/qml/editorwidgets/ValueRelation.qml
Labels: BUG, backport release-1_8

#1598 Respect project labeling engine settings when rendering canvas
  src/core/qgsquick/qgsquickmapcanvasmap.cpp
Labels: BUG, backport release-1_8

#1595 Harden git rev control
  src/core/androidplatformutilities.cpp
Labels: BUG, backport release-1_8

#1608 Add new gnss_* variables next to position_* variables
  src/core/expressioncontextutils.cpp
  src/core/expressioncontextutils.h
  src/core/featuremodel.cpp
  src/core/featuremodel.h
  src/qml/qgismobileapp.qml
Labels: backport release-1_8

#1623 When the project map theme has changed, refresh attribute form models
  src/core/attributeformmodel.h
  src/core/attributeformmodelbase.cpp
  src/core/attributeformmodelbase.h
  src/qml/OverlayFeatureFormDrawer.qml
Labels: BUG, backport release-1_8

#1618 Freehand fixes
  src/core/featuremodel.cpp
  src/core/featuremodel.h
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_8

#1544 Support for geometry digitizing when adding a child feature via relation editor
  src/core/featuremodel.cpp
  src/qml/DigitizingToolbar.qml
  src/qml/EmbeddedFeatureForm.qml
  src/qml/FeatureForm.qml
  src/qml/FeatureListForm.qml
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/CheckBox.qml
  src/qml/editorwidgets/DateTime.qml
  src/qml/editorwidgets/EditorWidgetBase.qml
  src/qml/editorwidgets/ExternalResource.qml
  src/qml/editorwidgets/Range.qml
  src/qml/editorwidgets/RelationEditor.qml
  src/qml/editorwidgets/RelationReference.qml
  src/qml/editorwidgets/TextEdit.qml
  src/qml/editorwidgets/ValueMap.qml
  src/qml/editorwidgets/ValueRelation.qml
  src/qml/geometry_editors/GeometryEditorsToolbar.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT, minor

#1629 Fix rubber band drawing precision issues
  src/core/linepolygonhighlight.cpp
  src/core/linepolygonhighlight.h
  src/core/qgssggeometry.cpp
  src/core/qgssggeometry.h
  src/core/rubberband.cpp
  src/core/rubberband.h
  src/qml/GeometryRenderer.qml
  src/qml/qgismobileapp.qml
Labels: BUG

#1625 NMEA follow up: improve elevation situation
  android/src/ch/opengis/qfield/QFieldActivity.java
  src/core/bluetoothreceiver.cpp
  src/core/bluetoothreceiver.h
  src/qml/PositionInformationView.qml
  src/qml/PositioningSettings.qml
  src/qml/QFieldSettings.qml
  src/qml/TransformedPositionSource.qml
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_8

#1642 Survive broken datetime widget configuration
  src/qml/editorwidgets/DateTime.qml
Labels: backport release-1_8

#1641 Support for opening individual vector/raster dataset in QField
  android/res/values/strings.xml
  android/src/ch/opengis/qfield/QFieldProjectActivity.java
  src/core/appinterface.cpp
  src/core/appinterface.h
  src/core/platformutilities.cpp
  src/core/platformutilities.h
  src/core/projectsource.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/core/qgsquick/qgsquickmapsettings.cpp
  src/core/qgsquick/qgsquickmapsettings.h
  src/core/utils/featureutils.cpp
  src/core/utils/featureutils.h
  src/qml/WelcomeScreen.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT
