Repository opengisch/QField, pull requests merged in 2021-02, with the labels that each got.

#1650 Fix snapping to vertices from layer with a CRS not matching that of the project
  src/core/snappingutils.cpp
Labels: BUG, backport release-1_8

#1651 SDK update to gain georeferenced PDF support as well as rendering speed gains
  CMakeLists.txt
  sdk.conf
Labels: ENHANCEMENT

#1654 Only show one decimal for PDOP, HDOP, VDOP values
  src/qml/PositionInformationView.qml
Labels: backport release-1_8

#1660 Fix permissions to add new file
  src/core/utils/fileutils.cpp
Labels: backport release-1_8

#1659 Demo Projects with UUIDs etc
  resources/demo_projects/advanced_bee_farming.qgs
  resources/demo_projects/basemaps/laax.gpkg
  resources/demo_projects/bees.gpkg
  resources/demo_projects/simple_bee_farming.qgs
Labels: backport release-1_8

#1668 Do not zoom/center to empty layer, hangs QField forever
  src/core/qgsquick/qgsquickmapsettings.cpp
Labels: backport release-1_8

#1674 Use QgsLayoutExporter's exportToPdf instead of a QPrinter
  src/core/qgismobileapp.cpp
Labels: ENHANCEMENT

#1708 Fixed a regression not showing the display string in value relation
  src/core/featurelistmodel.cpp
Labels: backport release-1_8, minor

#1725 Message log improvements
  src/core/messagelogmodel.cpp
  src/core/messagelogmodel.h
  src/qml/MessageLog.qml
  src/qml/qgismobileapp.qml
Labels: UX/UI, minor
