Repository opengisch/QField, pull requests merged in 2021-04, with the labels that each got.

#1818 Fix error response feedback
  src/core/qfieldcloudconnection.cpp
  src/core/qfieldcloudprojectsmodel.cpp
Labels: BUG, patch

#1819 A couple of position fixes
  src/core/featuremodel.cpp
  src/qml/CoordinateLocator.qml
  src/qml/DigitizingToolbar.qml
  src/qml/EmbeddedFeatureForm.qml
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-1_9, patch

#1824 Fix empty numeric fields saved as 0 instead of NULL
  src/core/attributeformmodelbase.cpp
  src/core/featuremodel.cpp
  src/qml/FeatureForm.qml
Labels: BUG, backport release-1_9

#1827 Fix and improve remembered values
  src/core/featuremodel.cpp
  src/core/featuremodel.h
Labels: BUG, backport release-1_9

#1830 Update SDK to catch update feature fix
  sdk.conf
Labels: backport release-1_9

#1832 Automatically close the features list when none are lefft after feature(s) deletion
  src/qml/FeatureListForm.qml
Labels: BUG, backport release-1_9

#1834 Catch transform errors
  src/core/qgismobileapp.cpp
  src/core/qgsquick/qgsquickmapcanvasmap.cpp
Labels: backport release-1_9

#1855 Fix use of relative paths by symbol layers during map canvas rendering
  src/core/qgsquick/qgsquickmapsettings.cpp
Labels: BUG, backport release-1_9

#1857 Relation editor widget UI/UX improvements
  src/core/referencingfeaturelistmodel.cpp
  src/core/referencingfeaturelistmodel.h
  src/qml/EmbeddedFeatureForm.qml
  src/qml/FeatureForm.qml
  src/qml/editorwidgets/RelationEditor.qml
  test/test_referencingfeaturelistmodel.cpp
Labels: BUG, UX/UI, backport release-1_9

#1867 Fix camera popup under feature form panels (fixes #1851)
  src/qml/editorwidgets/ExternalResource.qml
  src/qml/editorwidgets/RelationEditor.qml
Labels: BUG, backport release-1_9
