Repository opengisch/QField, pull requests merged in 2021-03, with the labels that each got.

#1729 Fix several textedit editor widget regressions
  src/qml/editorwidgets/TextEdit.qml
Labels: BUG, backport release-1_8

#1745 Update OSGeo4A SDK to grab latest GEOS and OpenSSL libs
  sdk.conf
Labels: backport release-1_9

#1748 SubModel fundamentally broken, fix it!
  src/core/snappingutils.cpp
  src/core/submodel.cpp
  src/core/submodel.h
  src/qml/editorwidgets/TextEdit.qml
Labels: BUG, backport release-1_9

#1747 Fix date widget not liking date-as-string value
  src/qml/editorwidgets/DateTime.qml
Labels: BUG, backport release-1_9

#1751 When an expression constraint lacks a description, add a generic tip to users
  src/core/attributeformmodelbase.cpp
Labels: backport release-1_9

#1753 Respect maximum length in text edit widget
  src/qml/editorwidgets/TextEdit.qml
Labels: BUG, backport release-1_9

#1756 Fix a couple of (harmless) errors when shutting down QField
  src/qml/WelcomeScreen.qml
  src/qml/qgismobileapp.qml
Labels: backport release-1_9

#1755 Fix missing translations
  src/core/finlandlocatorfilter.cpp
  src/core/locatormodelsuperbridge.cpp
  src/core/qgismobileapp.cpp
Labels: BUG, backport release-1_9

#1760 Dismiss toast message when clicking on it
  src/qml/qgismobileapp.qml
Labels: backport release-1_9

#1765 Reset rubberband after use
  src/qml/geometry_editors/SplitFeatureToolbar.qml
Labels: backport release-1_9

#1783 No map? Let's not crash
  src/core/qgismobileapp.cpp
Labels: backport release-1_9

#1777 Fix canvas follow location interfering with jump to feature / go to coordinate
  .github/workflows/continuous_integration.yml
  src/qml/MapCanvas.qml
  src/qml/qgismobileapp.qml
Labels: backport release-1_9

#1794 Navigation bar fixes
  src/qml/FeatureListForm.qml
  src/qml/NavigationBar.qml
Labels: BUG, backport release-1_9

#1806 Add missing tr() for the goto description (fixes #1805)
  src/core/locatormodelsuperbridge.cpp
Labels: BUG, backport release-1_9
