Repository opengisch/QField, pull requests merged in 2021-08, with the labels that each got.

#2063 Support UUID generator editor widget
  src/core/utils/stringutils.cpp
  src/core/utils/stringutils.h
  src/qml/FeatureForm.qml
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/CheckBox.qml
  src/qml/editorwidgets/DateTime.qml
  src/qml/editorwidgets/EditorWidgetBase.qml
  src/qml/editorwidgets/ExternalResource.qml
  src/qml/editorwidgets/Range.qml
  src/qml/editorwidgets/RelationReference.qml
  src/qml/editorwidgets/TextEdit.qml
  src/qml/editorwidgets/UuidGenerator.qml
  src/qml/editorwidgets/ValueMap.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#2071 Force using posix paths
  src/qml/editorwidgets/DateTime.qml
  src/qml/editorwidgets/ExternalResource.qml
Labels: BUG

#2088 Remember tracking settings values, revamp UI
  src/qml/LayerTreeItemProperties.qml
  src/qml/PageHeader.qml
  src/qml/PositioningSettings.qml
  src/qml/Tracking.qml
Labels: ENHANCEMENT

#2086 Add a complete-as-you-type mode to the relation combobox
  src/core/featurelistmodel.cpp
  src/core/featurelistmodel.h
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/RelationReference.qml
Labels: ENHANCEMENT

#2092 Allow sub-second, sub-meter tracking constraints
  src/core/tracker.cpp
  src/core/tracker.h
  src/core/trackingmodel.cpp
Labels: minor
