Repository opengisch/QField, pull requests merged in 2022-03, with the labels that each got.

#2568 Avoid dimming when moving mouse / pen around the screen
  src/core/screendimmer.cpp
Labels: backport release-2_0

#2564 Add cloud error class that wraps the error response within an object
  src/core/qfieldcloudconnection.cpp
  src/core/qfieldcloudconnection.h
  src/core/qfieldcloudprojectsmodel.h
Labels: qfieldcloud

#2575 Fix missing vertical grids when located in the QField app data directory
  src/core/platforms/platformutilities.cpp
Labels: backport release-2_0

#2586 Improve bookmark marker by using a Shape item instead of an SVG
  images/images.qrc
  images/themes/qfield/nodpi/ic_place_white_24dp.svg
  src/qml/BookmarkRenderer.qml
Labels: backport release-2_0

#2587 Allow users to add and edit bookmarks
  src/core/bookmarkmodel.cpp
  src/core/bookmarkmodel.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/qml/BookmarkHighlight.qml
  src/qml/BookmarkProperties.qml
  src/qml/BookmarkRenderer.qml
  src/qml/imports/Theme/Theme.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#2433 Support "show delete child button" configuration for relations
  src/qml/editorwidgets/relationeditors/relation_editor.qml
Labels: ENHANCEMENT

#2609 Print pdfs to the project folder
  src/core/qgismobileapp.cpp
Labels: backport release-2_0

#2617 Fix longstanding regression whereas length/area information is missing when digitizing features
  src/qml/qgismobileapp.qml
Labels: backport release-2_0

#2620 Sentry opt-out implementation
  .github/workflows/android.yml
  CMakeLists.txt
  platform/android/AndroidManifest.xml.in
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  src/app/CMakeLists.txt
  src/app/main.cpp
  src/core/CMakeLists.txt
  src/core/platforms/android/androidplatformutilities.cpp
  src/core/platforms/android/androidplatformutilities.h
  src/core/platforms/platformutilities.cpp
  src/core/platforms/platformutilities.h
  src/qml/MessageLog.qml
  src/qml/QFieldSettings.qml
  src/qml/WelcomeScreen.qml
Labels: backport release-2_0

#2631 Test both existance and readability of the QField (root) data dir
  src/core/qgismobileapp.cpp
Labels: backport release-2_0

#2646 Move assert to its righteous place
  src/core/qgismobileapp.cpp
Labels: backport release-2_0

#2647 Fix java crasher seen on sentry
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  platform/android/src/ch/opengis/qfield/QFieldUtils.java
Labels: backport release-2_0

#2650 Fix macos builds
  .github/workflows/desktop.yml
  .github/workflows/ios.yml
Labels: backport release-2_0

#2660 Reset rubber band upon a failed ring operation (fixes #2567)
  src/qml/geometry_editors/FillRingToolBar.qml
Labels: backport release-2_0

#2659 Make number edit widget's spin buttons less prone to go wild
  src/qml/editorwidgets/Range.qml
Labels: backport release-2_0

#2658 Do not double-compile value relation feature lists
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/RelationReference.qml
  src/qml/editorwidgets/ValueRelation.qml
Labels: backport release-2_0
