Repository opengisch/QField, pull requests merged in 2022-08, with the labels that each got.

#3155 Insure that private layers are not added to the legend (fixes #3154)
  src/core/layertreemodel.cpp
Labels: backport release-2_2

#3177 Fix resetting attributes on creation issue
  src/qml/qgismobileapp.qml
Labels: backport release-2_2

#3188 Let's get QField to draw outside of the box
  platform/android/build.gradle.in
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  src/core/CMakeLists.txt
  src/core/platforms/android/androidplatformutilities.cpp
  src/core/platforms/android/androidplatformutilities.h
  src/core/platforms/platformutilities.cpp
  src/core/platforms/platformutilities.h
  src/qml/DashBoard.qml
  src/qml/EmbeddedFeatureForm.qml
  src/qml/FeatureForm.qml
  src/qml/FeatureListForm.qml
  src/qml/NavigationBar.qml
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/PageHeader.qml
  src/qml/QFieldCloudPopup.qml
  src/qml/QFieldCloudScreen.qml
  src/qml/QFieldLocalDataPickerScreen.qml
  src/qml/QFieldSettings.qml
  src/qml/WelcomeScreen.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#3193 Disable local data picker on ios
  src/qml/WelcomeScreen.qml
Labels: needs documentation

#3213 Show visible features
  doc/dev.md
  images/images.qrc
  images/themes/qfield/nodpi/ic_list_black_24dp.svg
  images/themes/qfield/nodpi/ic_list_visible_black_24dp.svg
  src/core/multifeaturelistmodel.cpp
  src/core/multifeaturelistmodel.h
  src/qml/LayerTreeItemProperties.qml
Labels: ENHANCEMENT, minor

#3247 Allow position tracking on point layers
  src/core/featuremodel.cpp
  src/core/featuremodel.h
  src/core/layertreemodel.cpp
  src/core/rubberband.cpp
  src/core/rubberband.h
  src/core/tracker.cpp
  src/qml/LayerTreeItemProperties.qml
  src/qml/Tracking.qml
Labels: ENHANCEMENT, minor

#3249 Layer properties popup reorganizing
  src/qml/LayerTreeItemProperties.qml
  src/qml/Legend.qml
  src/qml/imports/Theme/QfButton.qml
Labels: UX/UI

#3262 Fix hidden {rule,category,graduation} symbols still identified on the map
  src/core/identifytool.cpp
Labels: ENHANCEMENT, minor

#3237 Remember map layer styling (opacity, labels visibility) across QField sessions
  src/core/layertreemodel.cpp
  src/core/projectinfo.cpp
  src/core/projectinfo.h
  src/core/qgismobileapp.cpp
  src/qml/LayerTreeItemProperties.qml
  src/qml/Legend.qml
Labels: ENHANCEMENT, minor

#3265 Configure the timeout to dim screen, rather than simple disabling it
  src/core/appinterface.cpp
  src/core/appinterface.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/core/screendimmer.cpp
  src/core/screendimmer.h
  src/qml/QFieldSettings.qml
  src/qml/imports/Theme/QfSlider.qml
  src/qml/imports/Theme/qmldir
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT, minor

#3270 Make the slider opacity use the new QfSlider widget
  src/qml/LayerTreeItemProperties.qml
Labels: ENHANCEMENT, minor

#3276 Measuring tool should respect the project's distance and area units type
  src/core/distancearea.cpp
  src/core/distancearea.h
  src/core/qgismobileapp.cpp
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, needs documentation, minor
