Repository opengisch/QField, pull requests merged in 2022-11, with the labels that each got.

#3586 Do not upload "all-access" to playstore
  .github/workflows/android.yml
Labels: backport release-2_5

#3590 Fix if condition in android workflow
  .github/workflows/android.yml
Labels: backport release-2_5

#3596 Fix crash when activating measuring tool in a number of projects
  src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
Labels: backport release-2_5

#3605 Fix crash when adding features on a vector layer that had been drawn onto an elevation profile
  src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
Labels: backport release-2_5

#3603 Submodel and feature form fix
  src/core/attributeformmodelbase.cpp
  src/core/submodel.cpp
  src/core/submodel.h
  src/qml/FeatureForm.qml
Labels: backport release-2_5

#3604 Taking into account dpi and device pixel ratio when drawing plots
  src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
Labels: backport release-2_5

#3616 Avoid running the QFieldCloud login shader effect when not visible
  src/qml/QFieldCloudLogin.qml
  src/qml/QFieldCloudPopup.qml
  src/qml/QFieldCloudScreen.qml
Labels: backport release-2_5

#3612 Fix outsized feature form field heights
  src/core/attributeformmodelbase.cpp
  src/qml/FeatureForm.qml
Labels: backport release-2_5

#3623 The attribute form model isn't a 2-level situation anymore, adjust root-tab constraint data
  src/core/attributeformmodelbase.cpp
Labels: backport release-2_5

#3624 Avoid connecting to model signals when submodel is disabled
  src/core/submodel.cpp
  src/core/submodel.h
Labels: backport release-2_5

#3620 QFieldCloud account registration in in-app browser
  src/qml/BrowserPanel.qml
  src/qml/QFieldCloudLogin.qml
  src/qml/qgismobileapp.qml
Labels: backport release-2_5

#3629 Feature form fixes
  src/core/submodel.cpp
  src/core/submodel.h
  src/qml/FeatureForm.qml
Labels: BUG, backport release-2_5

#3641 Fix incorrect storage of vertical speed as magnetic variation
  src/core/positioning/internalgnssreceiver.cpp
Labels: backport release-2_5

#3644 Fix multiline-enabled text editor widget
  src/qml/editorwidgets/TextEdit.qml
Labels: backport release-2_5

#3657 Better initial extent when opening individual datasets with single-point (or multiple points at same location) datasets
  src/core/qgismobileapp.cpp
Labels: BUG, backport release-2_5

#3662 Fix QML container not loading regression
  src/qml/FeatureForm.qml
Labels: backport release-2_5

#3686 Fix constraints not ignored within hidden containers
  src/core/attributeformmodelbase.cpp
Labels: BUG, backport release-2_5

#3685 Avoid feature model's double setFeature() calls when creating a new feature
  src/core/featuremodel.cpp
  src/core/featuremodel.h
Labels: BUG, backport release-2_5

#3680 Fix iOS bottom UI elements overlap with system bar
  src/core/platforms/platformutilities.cpp
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-2_5

#3696 When using the camera or gallery on iOS to fetch a photo, insure destination path is created
  src/core/platforms/ios/iospicturesource.mm
Labels: BUG, backport release-2_5

#3692 Fix password text field height clipped
  src/qml/imports/Theme/QfTextField.qml
Labels: BUG, backport release-2_5

#3690 Fix freeze (on slower device it can be 1-2sec) regression when clicking on layer tree items
  src/qml/FeatureForm.qml
Labels: BUG, backport release-2_5

#3687 Fix regression with the checkbox editor widget whereas clicking outside of the switch wouldn't change value
  src/qml/editorwidgets/CheckBox.qml
Labels: BUG, backport release-2_5

#3705 Keep the feature form model alive when hiding form to digitize child geometry
  src/qml/FeatureForm.qml
Labels: BUG, backport release-2_5

#3706 Insure that child containers of a tab with an expession-based visibility carry on the parent expression
  src/core/attributeformmodelbase.cpp
Labels: BUG

#3709 Geometry editor rubberband fix
  src/core/rubberband.cpp
  src/core/vertexmodel.cpp
  src/qml/geometry_editors/VertexEditorToolbar.qml
  src/qml/qgismobileapp.qml
Labels: BUG, backport release-2_5
