Repository opengisch/QField, pull requests merged in 2022-09, with the labels that each got.

#3283 Add a DateTime editor widget qml test
  src/app/CMakeLists.txt
  src/qml/CMakeLists.txt
  src/qml/imports/QFieldControls/qmldir
  test/CMakeLists.txt
  test/qml/tst_editorwidgets.qml
Labels: backport release-2_3

#3285 Allow all types of image to by selected on Android's gallery
  platform/android/src/ch/opengis/qfield/QFieldGalleryPictureActivity.java
Labels: backport release-2_3

#3286 Disable bluetooth support on iOS, that's simply not supported by Qt
  .github/workflows/ios.yml
Labels: backport release-2_3

#3294 Move the setPkgDataPath call around so it doesn't get overwritten by initQgis
  src/app/main.cpp
Labels: BUG, patch, backport release-2_3

#3280 Fix delta generation on NULL and 0
  doc/dev.md
  src/core/deltafilewrapper.cpp
  test/CMakeLists.txt
  test/test_deltafilewrapper.cpp
Labels: BUG, qfieldcloud, patch, backport release-2_3

#3292 Prevent random sorting of the cloud projects
  src/core/qfieldcloudprojectsmodel.cpp
Labels: BUG, qfieldcloud, patch, backport release-2_3

#3293 Give a hint that the projects list is empty
  src/qml/QFieldCloudScreen.qml
Labels: ENHANCEMENT, qfieldcloud, patch, backport release-2_3

#3304 Fix crash when the layer is invalid
  src/core/layertreemodel.cpp
Labels: BUG, patch, backport release-2_3

#3313 Handle static link to QCA ossl plugin on static builds
  cmake/qgis-cmake-wrapper.cmake
  src/app/CMakeLists.txt
  src/app/main.cpp
  vcpkg/overlay/qca/portfile.cmake
Labels: BUG, backport release-2_3

#3319 Fix dashboard buttons glitch on iOS
  src/qml/DashBoard.qml
Labels: backport release-2_3

#3317 Implement basic iOS local files / project support
  platform/ios/Info.plist.in
  src/core/platforms/ios/iosplatformutilities.h
  src/core/platforms/ios/iosplatformutilities.mm
  src/qml/WelcomeScreen.qml
Labels: backport release-2_3

#3303 Fetch public projects with a separate request
  src/core/qfieldcloudprojectsmodel.cpp
  src/core/qfieldcloudprojectsmodel.h
  src/qml/QFieldCloudScreen.qml
Labels: BUG, qfieldcloud, patch, backport release-2_3

#3370 [ios] deploy on release
  .github/workflows/ios.yml
Labels: backport release-2_3

#3374 Harmonize margins of changelog popup, which also avoids overlap with the status bar area
  src/qml/Changelog.qml
Labels: backport release-2_3
