Repository opengisch/QField, pull requests merged in 2022-05, with the labels that each got.

#2836 Refine map canvas and positioning menu item labels, add icons
  images/images.qrc
  images/themes/qfield/hdpi/ic_bookmark_black_24dp.png
  images/themes/qfield/mdpi/ic_bookmark_black_24dp.png
  images/themes/qfield/nodpi/ic_bookmark_black_24dp.svg
  images/themes/qfield/xhdpi/ic_bookmark_black_24dp.png
  images/themes/qfield/xxhdpi/ic_bookmark_black_24dp.png
  images/themes/qfield/xxxhdpi/ic_bookmark_black_24dp.png
  src/qml/qgismobileapp.qml
Labels: backport release-2_1

#2844 Fix broken view relation feature button regression
  src/qml/editorwidgets/RelationReference.qml
Labels: backport release-2_1

#2852 Display {jpg,png,tif,webp,pdf} thumbnails in the project/dataset picker activity
  CMakeLists.txt
  platform/android/src/ch/opengis/qfield/QFieldProjectListAdapter.java
  src/core/platforms/android/androidplatformutilities.cpp
Labels: Squash!

#2851 Guard from a ZIP path traversal attack
  platform/android/src/ch/opengis/qfield/QFieldUtils.java
Labels: backport release-2_1

#2872 Fix PGSYSCONFIGDIR handling
  src/core/qgismobileapp.cpp
Labels: backport release-2_1

#2874 Add missing handling of .jpeg extension
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
  src/core/qgismobileapp.h
Labels: backport release-2_1

#2879 Slightly improve handling of removal (sd card) storage in the project dataset picker
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
Labels: backport release-2_1

#2889 Allow copying bookmark details to clipboard, plus usuability improvements
  src/core/bookmarkmodel.cpp
  src/core/bookmarkmodel.h
  src/qml/BookmarkProperties.qml
  src/qml/imports/Theme/Theme.qml
Labels: backport release-2_1

#2895 Do *not* use qgis data directory as profile directory
  src/app/main.cpp
Labels: backport release-2_1

#2898 Add zoom to group in the legend properties
  src/core/layertreemodel.cpp
  src/core/layertreemodel.h
  src/qml/LayerTreeItemProperties.qml
Labels: ENHANCEMENT

#2899 Fix compass on rotated screen
  src/qml/LocationMarker.qml
Labels: backport release-2_1

#2902 When triggering a search result action (i.e. right-end buttons), close the search result
  src/qml/LocatorItem.qml
Labels: backport release-2_1

#2904 Fix versions-old regression on project file fonts loading
  src/core/qgismobileapp.cpp
Labels: backport release-2_1

#2907 Clear any search bar results when a new project is loaded to avoid issues
  src/qml/LocatorItem.qml
Labels: backport release-2_1

#2934 Measuring tool improvements
  src/core/distancearea.cpp
  src/core/distancearea.h
  src/core/rubberbandmodel.cpp
  src/core/rubberbandmodel.h
  src/core/utils/geometryutils.cpp
  src/core/utils/geometryutils.h
  src/qml/MeasuringTool.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#2945 QField should respect projects' coordinate display unit type
  resources/sample_projects/advanced_bee_farming.qgs
  resources/sample_projects/live_qfield_users_survey.qgs
  resources/sample_projects/simple_bee_farming.qgs
  scripts/cppcheck.sh
  src/core/CMakeLists.txt
  src/core/locator/gotolocatorfilter.cpp
  src/core/qgismobileapp.cpp
  src/core/utils/coordinatereferencesystemutils.cpp
  src/core/utils/coordinatereferencesystemutils.h
  src/core/utils/geometryutils.cpp
  src/core/utils/geometryutils.h
  src/core/utils/snappingutils.h
  src/core/utils/stringutils.cpp
  src/core/utils/stringutils.h
  src/qml/About.qml
  src/qml/BookmarkProperties.qml
  src/qml/BookmarkRenderer.qml
  src/qml/CoordinateLocator.qml
  src/qml/LayerTreeItemProperties.qml
  src/qml/NavigationHighlight.qml
  src/qml/NavigationInformationView.qml
  src/qml/NavigationRenderer.qml
  src/qml/PositionInformationView.qml
  src/qml/QFieldSettings.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT
