Repository opengisch/QField, pull requests merged in 2022-04, with the labels that each got.

#2687 Try to fix virtual keyboard sometimes not popping up when focusing on text input
  src/qml/QFieldCloudLogin.qml
  src/qml/imports/Theme/QfTextField.qml
Labels: backport release-2_0

#2705 Avoid throwing harmless but disturbing warning messages when typing into range editor widget
  src/qml/editorwidgets/Range.qml
Labels: backport release-2_0

#2724 Further improve the metrics popup, re-asks to get a clear(er) answer
  src/qml/About.qml
  src/qml/WelcomeScreen.qml
  src/qml/imports/Theme/QfButton.qml
  src/qml/qgismobileapp.qml
Labels: backport release-2_0

#2727 Remove crash prone feedback connection in the system loader scene
  src/core/platforms/android/androidplatformutilities.cpp
  src/qml/SystemLoader.qml
Labels: backport release-2_0

#2738 Avoid crashing when parsing a DownloadsProvider URI with a non-numerical ID
  platform/android/src/ch/opengis/qfield/QFieldUtils.java
Labels: backport release-2_0

#2745 Add a setting to disable display of bookmarks on the map
  src/qml/BookmarkHighlight.qml
  src/qml/QFieldSettings.qml
Labels: backport release-2_0

#2733 Implement send compressed folder and export project folder [to folder] functionality
  platform/android/res/menu/project_folder_menu.xml
  platform/android/res/menu/project_item_menu.xml
  platform/android/res/values/strings.xml
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
  platform/android/src/ch/opengis/qfield/QFieldProjectListAdapter.java
  platform/android/src/ch/opengis/qfield/QFieldUtils.java
Labels: backport release-2_0

#2750 Add a up/back button in the open local project/dataset activity navigation bar
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
Labels: backport release-2_0

#2752 OK -> I agree
  src/qml/WelcomeScreen.qml
Labels: backport release-2_0

#2740 Allow for pictures taken (through camera or gallery) to be restricted to a maximum width/height
  src/core/appinterface.cpp
  src/core/appinterface.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/qml/editorwidgets/ExternalResource.qml
Labels: ENHANCEMENT

#2755 Fix focused feature issue when running out of features hitting previous/next buttons
  src/qml/NavigationBar.qml
Labels: backport release-2_0

#2756 Insure that our rubber bands take device pixel ratio into account to harmonize rendering on all screen densities
  src/core/rubberband.cpp
  src/core/rubberband.h
  src/core/sgrubberband.cpp
  src/core/sgrubberband.h
  src/qml/qgismobileapp.qml
Labels: backport release-2_0

#2754 Storage help
  platform/android/AndroidManifest.xml.in
  platform/android/build.gradle.in
  platform/android/res/values/colors.xml
  platform/android/res/values/strings.xml
  platform/android/res/values/styles.xml
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
Labels: backport release-2_0

#2769 Implement a fullscreen mode on desktop, toggled via F11
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#2771 Fix QfButton disabled state's border color
  src/qml/imports/Theme/QfButton.qml
Labels: backport release-2_0

#2786 Fix QField unable to import project from a number of ZIP files, rename functions
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
  platform/android/src/ch/opengis/qfield/QFieldUtils.java
Labels: backport release-2_0

#2788 Fix back button following migration to AppCompatActivity
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
Labels: backport release-2_0

#2797 Changelog ordering improvements
  src/core/changelogcontents.cpp
Labels: backport release-2_0, backport release-2_1

#2573 Improve help text by replacing "local cloud layers" with "local layers"
  src/qml/QFieldCloudPopup.qml
Labels: ENHANCEMENT, qfieldcloud, minor

#2805 Set a nice QField-green default app-wide hyperlink color
  src/core/qgismobileapp.cpp
  src/qml/About.qml
  src/qml/QFieldCloudLogin.qml
  src/qml/QFieldCloudPopup.qml
  src/qml/QFieldSettings.qml
Labels: backport release-2_1

#2807 Improve .pg_service.conf logic, prioritize the more secure location
  src/core/qgismobileapp.cpp
Labels: backport release-2_1

#2812 Add missing handling of .tiff extension
  platform/android/AndroidManifest.xml.in
  platform/android/src/ch/opengis/qfield/QFieldProjectActivity.java
  src/core/qgismobileapp.h
Labels: backport release-2_1

#2822 Hide the "New user?" registration link if already signed in
  src/qml/QFieldCloudLogin.qml
  src/qml/qgismobileapp.qml
Labels: qfieldcloud, backport release-2_1

#2821 Always show the changelog once per version update
  src/qml/Changelog.qml
Labels: backport release-2_1

#2825 Append CRS informatio when copying map canvas point/position location to the clipboard
  src/qml/qgismobileapp.qml
Labels: backport release-2_1

#2828 Make sure the "Locked Geometry" setting is respected when adding/deleting/duplicating/moving features
  src/core/multifeaturelistmodelbase.cpp
  src/qml/Legend.qml
  src/qml/NavigationBar.qml
  src/qml/qgismobileapp.qml
Labels: BUG
