Repository opengisch/QField, pull requests merged in 2023-12, with the labels that each got.

#4805 Snap to common angle
  images/images.qrc
  images/themes/qfield/nodpi/ic_common_angle_white_24dp.svg
  src/core/rubberbandmodel.cpp
  src/core/rubberbandmodel.h
  src/core/settings.cpp
  src/core/settings.h
  src/qml/CoordinateLocator.qml
  src/qml/qgismobileapp.qml
Labels: needs documentation

#4835 Update Android NDK (r25) to match what is used in pre-built Qt libraries
  .docker/android_dev/Dockerfile
  .github/workflows/android.yml
  cmake/Platform.cmake
  scripts/build-vcpkg.sh
Labels: backport release-3_1

#4842 Sentry update
  .github/workflows/android.yml
  platform/android/build.gradle.in
Labels: backport release-3_1

#4847 Guard against null object when checking permissions
  src/core/positioning/bluetoothdevicemodel.cpp
  src/core/positioning/bluetoothreceiver.cpp
  src/core/positioning/internalgnssreceiver.cpp
Labels: backport release-3_1

#4858 Fix confusing 'snap to 45 degree' toast when opening QField
  src/qml/qgismobileapp.qml
Labels: backport release-3_1

#4857 Add an additional safeguard when the barcode decoder attempts to process a video frame
  src/core/barcodedecoder.cpp
Labels: backport release-3_1

#4872 Fix lingering artifact when clearing navigation destination
  src/qml/LinePolygon.qml
Labels: backport release-3_1

#4877 Properly cancel geometry editor's fill ring and split feature tools
  src/qml/geometryeditors/FillRing.qml
  src/qml/geometryeditors/SplitFeature.qml
Labels: backport release-3_1

#4878 Disable map canvas interaction when the QFieldCloud projects panel and the local data picker panel are visible too
  src/qml/qgismobileapp.qml
Labels: backport release-3_1

#4875 Fix coordinate cursor locked to position not sticking to position
  src/qml/CoordinateLocator.qml
Labels: backport release-3_1

#4886 Allow for children to be added to a parent feature being added but not yet created
  src/core/attributeformmodel.cpp
  src/core/attributeformmodel.h
  src/core/attributeformmodelbase.cpp
  src/core/attributeformmodelbase.h
  src/core/featuremodel.cpp
  src/core/referencingfeaturelistmodel.cpp
  src/core/referencingfeaturelistmodel.h
  src/qml/editorwidgets/RelationReference.qml
  src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
  src/qml/editorwidgets/relationeditors/relation_editor.qml
Labels: ENHANCEMENT
