Repository opengisch/QField, pull requests merged in 2023-09, with the labels that each got.

#4546 Brand new search bar active layer feature matching functionality + UI/UX improvements
  src/core/CMakeLists.txt
  src/core/locator/activelayerfeatureslocatorfilter.cpp
  src/core/locator/activelayerfeatureslocatorfilter.h
  src/core/locator/locatormodelsuperbridge.cpp
  src/core/locator/locatormodelsuperbridge.h
  src/qml/LocatorItem.qml
  src/qml/LocatorSettings.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, needs documentation

#4589 Brand new tracker functionality: maximum distance tolerance
  src/core/tracker.cpp
  src/core/tracker.h
  src/core/trackingmodel.cpp
  src/core/trackingmodel.h
  src/qml/PositioningSettings.qml
  src/qml/TrackingSession.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#4560 Move Orthometric from device settings into Vertical grid shift correction combobox
  src/core/positioning/nmeagnssreceiver.cpp
  src/core/positioning/positioning.cpp
  src/core/positioning/positioning.h
  src/core/qgismobileapp.cpp
  src/qml/PositioningInformationView.qml
  src/qml/PositioningSettings.qml
  src/qml/QFieldSettings.qml
  src/qml/qgismobileapp.qml
  test/qml/tst_positioning.qml
Labels: needs documentation

#4584 Brand new geometry editor' erase tool functionality
  images/images.qrc
  images/themes/qfield/nodpi/ic_erase_tool_white_24dp.svg
  images/themes/qfield/nodpi/ic_size_large_white_24dp.svg
  images/themes/qfield/nodpi/ic_size_medium_white_24dp.svg
  images/themes/qfield/nodpi/ic_size_small_white_24dp.svg
  src/core/rubberbandmodel.cpp
  src/core/utils/geometryutils.cpp
  src/core/utils/geometryutils.h
  src/qml/CloseTool.qml
  src/qml/GeometryEditorsToolbar.qml
  src/qml/geometryeditors/Erase.qml
  src/qml/geometryeditors/FillRing.qml
  src/qml/geometryeditors/Reshape.qml
  src/qml/geometryeditors/SplitFeature.qml
  src/qml/geometryeditors/VertexEditor.qml
  src/qml/imports/QFieldControls/+Qt5/CodeReader.qml
  src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml
  src/qml/imports/QFieldControls/+Qt6/CodeReader.qml
  src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
  src/qml/imports/Theme/Theme.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#4594 Implement digitizing throuhg volume keys on Android devices
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  src/core/appinterface.h
  src/core/platforms/android/androidplatformutilities.cpp
  src/core/platforms/android/androidplatformutilities.h
  src/core/platforms/platformutilities.h
  src/qml/DigitizingToolbar.qml
  src/qml/QFieldSettings.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT
