Repository opengisch/QField, pull requests merged in 2023-10, with the labels that each got.

#4590 Allow for tracking session to be resumed (inc. across QField restarts)
  src/core/geometry.cpp
  src/core/layertreemapcanvasbridge.cpp
  src/core/projectinfo.cpp
  src/core/projectinfo.h
  src/core/tracker.cpp
  src/core/tracker.h
  src/core/trackingmodel.cpp
  src/core/trackingmodel.h
  src/qml/LayerTreeItemProperties.qml
  src/qml/TrackerSettings.qml
  src/qml/TrackingSession.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#4617 Significant optimization in handling of rubber band and line/polygon items
  src/core/linepolygonhighlight.cpp
  src/core/linepolygonhighlight.h
  src/core/rubberband.cpp
  src/core/rubberband.h
Labels: backport release-3_0

#4616 Fix handling of non-HTML text values having had links inserted (fixes #4615)
  src/core/utils/stringutils.cpp
  src/core/utils/stringutils.h
  src/qml/editorwidgets/TextEdit.qml
Labels: backport release-3_0

#4623 Fix missing inner ring outlines when highlighting polygons
  src/core/qgssggeometry.cpp
Labels: backport release-3_0

#4624 Do not block all stylus-driven map canvas click when feature form is visible, only block those falling under the feature form
  src/qml/qgismobileapp.qml
Labels: backport release-3_0

#4628 Use screen's physical DPI value again, android regression fixed in Qt 6.5.3
  src/core/qgsquick/qgsquickelevationprofilecanvas.cpp
  src/core/qgsquick/qgsquickmapcanvasmap.cpp
Labels: backport release-3_0

#4610 Clear WebView's cache on Android to avoid interference with authentication methods
  src/core/locator/activelayerfeatureslocatorfilter.cpp
  src/qml/BrowserPanel.qml
  src/qml/qgismobileapp.qml
Labels: backport release-3_0

#4638 When resetting the attribute form model, clear the containers QMap to avoid crashers
  src/core/attributeformmodelbase.cpp
Labels: backport release-3_0

#4637 Fix iOS release
  .github/workflows/ios.yml
Labels: backport release-3_0

#4643 Fix setting an int property to a string value breaks children deletion
  src/qml/editorwidgets/relationeditors/ordered_relation_editor.qml
  src/qml/editorwidgets/relationeditors/relation_editor.qml
Labels: backport release-3_0

#4646 Re-add background rectangle to deal with (now rare but still present) Qt flow glitches
  src/qml/FeatureForm.qml
Labels: backport release-3_0

#4645 Safeguard from triggering needless feature gathering when referincing feature list model gets passed the same feature
  src/core/referencingfeaturelistmodel.cpp
Labels: backport release-3_0

#4651 Fix calendar popup's {previous,next} {month,year} buttons on Qt6
  src/qml/imports/QFieldControls/+Qt6/CalendarPanel.qml
Labels: backport release-3_0

#4652 Revert increased identify search radius now that Qt6 DPI issue is resolved
  src/core/identifytool.cpp
  src/qml/qgismobileapp.qml
Labels: backport release-3_0

#4657 Use the preferred openstreetmap URL to improve performance and caching
  resources/sample_projects/live_qfield_users_survey.qgs
  src/core/qgismobileapp.cpp
Labels: backport release-3_0

#4660 Fix wrong user/password state misrepresented as expired session
  src/core/qfieldcloudconnection.cpp
Labels: backport release-3_0

#4664 Fix initiation of fill ring geometry editor, Qt6 isn't tolerant
  src/qml/geometryeditors/FillRing.qml
Labels: backport release-3_0

#4667 Fix missing debug symbols on sentry
  .github/workflows/android.yml
Labels: backport release-3_0

#4674 Use a better logic when building a rubber band model from a polygon geometry
  src/core/rubberbandmodel.cpp
Labels: backport release-3_0

#4676 Fix rubber band polygon highlight going missing due to coordinate distance fail
  src/core/qgssggeometry.cpp
  src/core/sgrubberband.cpp
Labels: backport release-3_0

#4675 Fix rubber band display 'glitchy' following optimization
  src/core/linepolygonhighlight.cpp
  src/core/rubberband.cpp
Labels: backport release-3_0

#4681 Move the magnetometer reading into the c++ positioning class, add @{position,gnss}_orientation variable
  src/core/appinterface.cpp
  src/core/appinterface.h
  src/core/positioning/gnsspositioninformation.cpp
  src/core/positioning/gnsspositioninformation.h
  src/core/positioning/positioning.cpp
  src/core/positioning/positioning.h
  src/core/utils/expressioncontextutils.cpp
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/qml/PositioningPreciseView.qml
  src/qml/editorwidgets/+Qt5/ExternalResource.qml
  src/qml/editorwidgets/+Qt6/ExternalResource.qml
  src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml
  src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, needs documentation

#4685 Add QField camera UI to toggle geotagging
  src/qml/imports/QFieldControls/+Qt5/QFieldCamera.qml
  src/qml/imports/QFieldControls/+Qt6/QFieldCamera.qml
Labels: ENHANCEMENT

#4688 Update app icon
  CMakeLists.txt
Labels: backport release-3_0

#4670 Update local project from archive functionality
  platform/android/res/menu/project_folder_menu.xml
  platform/android/res/menu/project_item_menu.xml
  platform/android/res/menu/project_menu.xml
  platform/android/res/values/strings.xml
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  src/core/platforms/android/androidplatformutilities.cpp
  src/core/platforms/android/androidplatformutilities.h
  src/core/platforms/platformutilities.cpp
  src/core/platforms/platformutilities.h
  src/qml/QFieldLocalDataPickerScreen.qml
Labels: ENHANCEMENT

#4696 Fix problematic image orientation when maximum image size is enabled
  src/core/distancearea.cpp
  src/core/locator/activelayerfeatureslocatorfilter.cpp
  src/core/locator/bookmarklocatorfilter.cpp
  src/core/locator/expressioncalculatorlocatorfilter.cpp
  src/core/locator/featureslocatorfilter.cpp
  src/core/locator/gotolocatorfilter.cpp
  src/core/qfieldcloudprojectsmodel.cpp
  vcpkg/overlay/qgis-qt6/exif_orientation_fix.patch
  vcpkg/overlay/qgis-qt6/portfile.cmake
Labels: backport release-3_0

#4694 Fix HTML widget not loading anymore
  src/qml/FeatureForm.qml
Labels: backport release-3_0

#4701 Fix display of rubber band and geometry highlight on rotated canvas
  src/core/linepolygonhighlight.cpp
  src/core/rubberband.cpp
Labels: backport release-3_0

#4712 Fix significant project load regressions when multiple layout legends are present
  vcpkg/overlay/qgis-qt6/layout_fix.patch
  vcpkg/overlay/qgis-qt6/portfile.cmake
Labels: backport release-3_0
