Repository opengisch/QField, pull requests merged in 2023-04, with the labels that each got.

#4124 Fix relation combobox add button's icon dark theme color
  src/qml/RelationCombobox.qml
Labels: backport release-2_7

#4137 Fix multi-select value relation editor widget with dark theme
  src/qml/editorwidgets/ValueRelation.qml
Labels: backport release-2_7

#4134 Fix header bar title overflowing into form when adding features
  src/qml/FeatureForm.qml
Labels: backport release-2_7

#4136 Fix QFieldCloud layer packaging feedback dialog text color with dark theme
  src/qml/QFieldCloudPackageLayersFeedback.qml
Labels: backport release-2_7

#4135 Fix follow orientation math to avoid a refresh on every minor compass value change
  src/qml/qgismobileapp.qml
Labels: backport release-2_7

#4152 Fix location movement marker not centered when rotated
  src/qml/LocationMarker.qml
Labels: backport release-2_7

#4148 Add a nifty expression calculator in the search bar
  src/core/CMakeLists.txt
  src/core/locator/expressioncalculatorlocatorfilter.cpp
  src/core/locator/expressioncalculatorlocatorfilter.h
  src/core/locator/locatormodelsuperbridge.cpp
Labels: ENHANCEMENT

#4138 Insure that the attribute form has all the context needed to generate default values
  src/core/attributeformmodelbase.cpp
  src/core/featuremodel.cpp
  src/core/featuremodel.h
Labels: backport release-2_7

#4131 Feature form optimization
  src/qml/FeatureForm.qml
Labels: backport release-2_7

#4169 Ready, toast, action!
  src/qml/Toast.qml
  src/qml/imports/Theme/QfButton.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: ENHANCEMENT

#4175 Reload last opened / default project on launch functionality
  src/core/appinterface.cpp
  src/core/appinterface.h
  src/core/platforms/platformutilities.cpp
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
  src/core/qgsquick/qgsquickmapcanvasmap.cpp
  src/qml/VisibilityFadingRow.qml
  src/qml/WelcomeScreen.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#4182 NMEA sentence logging functionality
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
  src/core/platforms/ios/iosplatformutilities.mm
  src/core/platforms/platformutilities.cpp
  src/core/positioning/abstractgnssreceiver.h
  src/core/positioning/nmeagnssreceiver.cpp
  src/core/positioning/nmeagnssreceiver.h
  src/core/positioning/positioning.cpp
  src/core/positioning/positioning.h
  src/qml/PositioningSettings.qml
  src/qml/QFieldSettings.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#4186 Store snapped vector layer as a QPointer<QgsVectorLayer>
  src/core/snappingresult.cpp
  src/core/snappingresult.h
Labels: backport release-2_7

#4188 Safeguard from crashing when an attribute form setData refers to out-of-model index
  src/core/attributeformmodelbase.cpp
Labels: backport release-2_7

#4198 Do not assume that the map canvas fills the whole screen when handling follow location maths
  src/qml/qgismobileapp.qml
Labels: backport release-2_7

#4204 Remove offending qInfo()
  src/core/layerobserver.cpp
Labels: backport release-2_7

#4199 Scene bottom margin improvements (i.e. avoid overlap with iOS navigation bar)
  src/qml/About.qml
  src/qml/FeatureForm.qml
  src/qml/FeatureListForm.qml
  src/qml/MessageLog.qml
  src/qml/OverlayFeatureFormDrawer.qml
  src/qml/QFieldCloudScreen.qml
  src/qml/QFieldLocalDataPickerScreen.qml
  src/qml/QFieldSettings.qml
  src/qml/WelcomeScreen.qml
  src/qml/qgismobileapp.qml
Labels: backport release-2_7

#4200 When re-opening the import URL dialog, clear previous URL
  src/qml/QFieldLocalDataPickerScreen.qml
Labels: backport release-2_7

#4192 Feature list sorting capability
  src/core/identifytool.cpp
  src/core/multifeaturelistmodelbase.cpp
Labels: ENHANCEMENT, needs documentation

#4203 Insure a non-averaged position vertex is added when accepting geometry upon hitting the accept/confirm button
  src/qml/DigitizingToolbar.qml
Labels: backport release-2_7

#4226 Delay creation of the bluetooth discovery agent until we need it
  src/core/positioning/bluetoothdevicemodel.cpp
  src/core/positioning/bluetoothdevicemodel.h
Labels: backport release-2_7

#4214 Add support for Happy IMU correction
  src/core/positioning/gnsspositioninformation.cpp
  src/core/positioning/gnsspositioninformation.h
  src/core/positioning/nmeagnssreceiver.cpp
  src/core/positioning/nmeagnssreceiver.h
  test/nmea_server/happyWithIMU.txt
  test/qml/tst_positioning.qml
  test/test_qml.cpp
Labels: ENHANCEMENT
