Repository opengisch/QField, pull requests merged in 2023-03, with the labels that each got.

#3999 Non-native QML camera enhancements
  images/images.qrc
  images/themes/qfield/nodpi/ic_flash_auto_black_24dp.svg
  images/themes/qfield/nodpi/ic_flash_off_black_24dp.svg
  images/themes/qfield/nodpi/ic_flash_on_black_24dp.svg
  src/core/appinterface.cpp
  src/core/platforms/android/androidplatformutilities.cpp
  src/core/platforms/android/androidresourcesource.cpp
  src/qml/Changelog.qml
  src/qml/QFieldCamera.qml
  src/qml/QFieldSettings.qml
  src/qml/imports/Theme/QfToolButton.qml
Labels: ENHANCEMENT

#4003 Allow opening of video attachment in external editor, restore empty image icon
  src/qml/editorwidgets/ExternalResource.qml
Labels: ENHANCEMENT

#4027 Import from URL action
  CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/appinterface.cpp
  src/core/appinterface.h
  src/core/platforms/platformutilities.cpp
  src/core/utils/ziputils.cpp
  src/core/utils/ziputils.h
  src/qml/BusyOverlay.qml
  src/qml/Changelog.qml
  src/qml/QFieldLocalDataPickerScreen.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
Labels: needs documentation, backport release-2_6

#4031 Fix missing font declaration for import ULR dialog leading to tiny buttons
  src/qml/QFieldLocalDataPickerScreen.qml
Labels: backport release-2_7

#4030 Implement system dark theme detection on iOS
  src/core/platforms/ios/iosplatformutilities.h
  src/core/platforms/ios/iosplatformutilities.mm
Labels: backport release-2_7

#4036 Revert "Absence of data is not 0, use NaN"
  src/core/rubberbandmodel.cpp
Labels: backport release-2_7

#4045 Give the rotation threshold a higher value
  src/qml/MapCanvas.qml
Labels: backport release-2_7

#4056 Account for canvas rotation when moving features (fix #4038)
  src/qml/qgismobileapp.qml
Labels: backport release-2_7

#4058 Fallback when relation id is not set
  src/core/CMakeLists.txt
  src/core/qgismobileapp.cpp
  src/core/utils/relationutils.cpp
  src/core/utils/relationutils.h
  src/qml/editorwidgets/RelationReference.qml
Labels: backport release-2_7

#4054 Added more detailed logs what is going on when creating deltas
  src/core/deltafilewrapper.cpp
  src/core/layerobserver.cpp
  src/core/layerobserver.h
Labels: backport release-2_7

#4072 Sensors support in QField!
  images/images.qrc
  images/themes/qfield/nodpi/ic_sensor_off_black_24dp.svg
  images/themes/qfield/nodpi/ic_sensor_on_black_24dp.svg
  src/core/CMakeLists.txt
  src/core/qgismobileapp.cpp
  src/core/sensorlistmodel.cpp
  src/core/sensorlistmodel.h
  src/core/tracker.cpp
  src/core/tracker.h
  src/core/trackingmodel.cpp
  src/core/trackingmodel.h
  src/qml/PositioningSettings.qml
  src/qml/SensorInformationView.qml
  src/qml/Tracking.qml
  src/qml/imports/Theme/Theme.qml
  src/qml/qgismobileapp.qml
  src/qml/qml.qrc
  vcpkg/overlay/qgis-qt6/portfile.cmake
  vcpkg/overlay/qgis-qt6/sensor.patch
  vcpkg/overlay/qgis/portfile.cmake
  vcpkg/overlay/qgis/sensor.patch
Labels: ENHANCEMENT

#4096 Fix combobox item icon not following dark theme setting
  src/qml/PositioningDeviceSettings.qml
  src/qml/QFieldSettings.qml
Labels: backport release-2_7
