Repository opengisch/QField, pull requests merged in 2023-05, with the labels that each got.

#4253 Add a check for a valid layer
  src/core/utils/relationutils.cpp
Labels: backport release-2_7

#4289 Add `FlatLayerTreeModel::Visible` to be refreshed in QML on data change
  src/core/layertreemodel.cpp
Labels: BUG, patch, backport release-2_8

#4291 Fix checkbox editor widget losing binding to value (fixes #4287)
  src/qml/editorwidgets/CheckBox.qml
Labels: backport release-2_8

#4308 Attribute values need to be reset to have their default value calculated by QGIS
  src/core/featuremodel.cpp
Labels: backport master
