Repository opengisch/QField, pull requests merged in 2024-03, with the labels that each got.

#5095 Fix type leading to erroneous geotagging (fixes #5093)
  src/core/utils/fileutils.cpp
Labels: backport release-3_2

#5098 Fix autopush timer interval value
  src/core/qfieldcloudprojectsmodel.cpp
  src/qml/QFieldCloudPopup.qml
Labels: backport release-3_2

#5099 Try enabling Bluetooth on Windows
  .github/workflows/windows.yml
Labels: backport release-3_2

#5113 Fix handling of empty string in the value relation editor widget
  src/core/featurechecklistmodel.cpp
Labels: backport release-3_2

#5107 Do not disable stylus hovering when mouse acts as touchscreen
  src/qml/qgismobileapp.qml
Labels: backport release-3_2

#5119 Fix changes list popup looking broken when empty
  src/core/deltalistmodel.cpp
  src/core/deltalistmodel.h
  src/qml/QFieldCloudDeltaHistory.qml
Labels: backport release-3_2

#5115 Strip HTML when receiving HTML server errors in cloud API
  src/core/qfieldcloudconnection.cpp
Labels: backport release-3_2

#5040 Performance boost when downloading packages
  src/core/qfieldcloudprojectsmodel.cpp
  src/core/utils/fileutils.h
  test/test_deltafilewrapper.cpp
Labels: backport release-3_2

#5131 Avoid last averaged position not taken into account when adding vertex
  src/core/positioning/positioning.cpp
Labels: backport release-3_2

#5127 Insure that the positioning information panel respects project distance unit type for altitude and accuracy
  src/qml/PositioningInformationView.qml
Labels: backport release-3_2

#5126 Add a shield/background to the busy indicator message to increase readability
  src/qml/BusyOverlay.qml
Labels: backport release-3_2

#5139 Prevent deltas having empty strings as WKT geometry
  src/core/deltafilewrapper.cpp
Labels: feedback

#5141 Now that we allow children creation prior to parent creation, we need to update default values to take possible children into consideration
  src/core/featuremodel.cpp
Labels: backport release-3_2

#5136 Only show the attachment widget's image frame for supported types by Qt
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/qml/editorwidgets/+Qt5/ExternalResource.qml
  src/qml/editorwidgets/+Qt6/ExternalResource.qml
Labels: backport release-3_2

#5140 Grouping functionality for the value relation editor widget
  src/core/featurelistmodel.cpp
  src/core/featurelistmodel.h
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/ValueRelation.qml
Labels: ENHANCEMENT, needs documentation

#5138 Implement a finger tap digitizing mode
  src/qml/QFieldSettings.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT, needs documentation
