Repository opengisch/QField, pull requests merged in 2024-08, with the labels that each got.

#5515 Fix current_parent_* for (embedded) feature model
  src/core/attributeformmodelbase.cpp
  src/core/featuremodel.cpp
Labels: backport release-3_3

#5520 Add camera resolution picker to QField's own camera
  images/images.qrc
  images/themes/qfield/nodpi/ic_camera_resolution_black_24dp.svg
  images/themes/qfield/nodpi/ic_camera_settings_black_24dp.svg
  src/qml/QFieldCamera.qml
  src/qml/imports/Theme/QfToolButtonDrawer.qml
Labels: ENHANCEMENT

#5535 Fix loss of images when merging patches against pre-existing create/patch deltas
  src/core/deltafilewrapper.cpp
  src/core/deltafilewrapper.h
  test/test_deltafilewrapper.cpp
Labels: backport release-3_3

#5542 Allow for users to manually push images/PDF files to the cloud from the project folder panel
  src/core/utils/qfieldcloudutils.h
  src/qml/QFieldLocalDataPickerScreen.qml
Labels: backport release-3_3

#5531 Improve logic and handling of of attachments upload to QFieldCloud
  .github/workflows/linux.yml
  platform/android/AndroidManifest.xml.in
  src/core/qfieldcloudconnection.cpp
  src/core/qfieldcloudconnection.h
  src/core/utils/qfieldcloudutils.cpp
  src/core/utils/qfieldcloudutils.h
  src/qml/qgismobileapp.qml
Labels: backport release-3_3

#5547 Fix snapping result point reprojection when current layer has a Z/M dimension
  src/core/utils/snappingutils.cpp
Labels: backport release-3_3

#5543 Value {map, relation} editor widget: fix representation problem with < character
  src/core/utils/stringutils.cpp
  src/core/utils/stringutils.h
  src/qml/RelationCombobox.qml
  src/qml/editorwidgets/ValueMap.qml
  test/test_stringutils.cpp
Labels: backport release-3_3

#5553 Bump android version to 34
  .docker/android_dev/Dockerfile
  .github/workflows/android.yml
  cmake/Platform.cmake
Labels: backport release-3_3

#5555 Harmonize handling of QField's (multi)value relation editor widget with that of QGIS
  src/core/featurechecklistmodel.cpp
  src/qml/editorwidgets/ValueRelation.qml
Labels: backport release-3_3

#5571 Hard exit reboot
  images/images.qrc
  images/themes/qfield/nodpi/ic_shutdown_24dp.svg
  src/qml/WelcomeScreen.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#5574 Search cloud projects list functionality
  src/core/qfieldcloudprojectsmodel.cpp
  src/core/qfieldcloudprojectsmodel.h
  src/qml/QFieldCloudScreen.qml
  src/qml/imports/Theme/QfSearchBar.qml
  src/qml/imports/Theme/qmldir
  src/qml/qml.qrc
Labels: ENHANCEMENT

#5587 Fix cloud user information context when loading a new cloud project
  src/core/projectinfo.cpp
  src/core/projectinfo.h
  src/qml/qgismobileapp.qml
Labels: backport release-3_3

#5593 Save/restore edited project variables
  src/core/expressionvariablemodel.cpp
  src/core/expressionvariablemodel.h
  src/core/projectinfo.cpp
  src/core/projectinfo.h
  src/core/utils/expressioncontextutils.cpp
  src/qml/VariableEditor.qml
Labels: ENHANCEMENT, needs documentation

#5595 Expression template support for title and copyright decorations
  src/core/expressionevaluator.cpp
  src/core/expressionevaluator.h
  src/qml/editorwidgets/ExternalResource.qml
  src/qml/qgismobileapp.qml
  test/CMakeLists.txt
  test/test_expressionevaluator.cpp
Labels: ENHANCEMENT

#5596 Add basic text stamping functionality on photos taken by QField camera
  images/images.qrc
  images/themes/qfield/nodpi/ic_text_black_24dp.svg
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/core/utils/positioningutils.cpp
  src/core/utils/positioningutils.h
  src/qml/QFieldCamera.qml
  src/qml/QFieldSettings.qml
  src/qml/editorwidgets/ExternalResource.qml
Labels: ENHANCEMENT
