Repository opengisch/QField, pull requests merged in 2025-05, with the labels that each got.

#6226 Implement qfield scheme on iOS
  platform/ios/Info.plist.in
  src/core/CMakeLists.txt
  src/core/qfieldurlhandler.cpp
  src/core/qfieldurlhandler.h
  src/core/qgismobileapp.cpp
  src/core/qgismobileapp.h
Labels: ENHANCEMENT

#6234 Fix geometry editor's eraser tool when using freehand mode
  src/qml/qgismobileapp.qml
Labels: backport release-3_5

#6208 Unlock feature identification on raster layers capable of returning features (WMS, ArcGIS Map Server, etc.)
  src/core/featuremodel.cpp
  src/core/identifytool.cpp
  src/core/identifytool.h
  src/core/multifeaturelistmodelbase.cpp
  src/core/multifeaturelistmodelbase.h
  src/qml/NavigationBar.qml
Labels: ENHANCEMENT

#6290 Fix minimum API level for foreground service type
  platform/android/src/ch/opengis/qfield/QFieldPositioningService.java
Labels: backport release-3_6

#6293 Better image decorator placement on short heights & fix toast logics
  src/qml/Toast.qml
  src/qml/qgismobileapp.qml
Labels: backport release-3_6

#6294 Avoid scary clipboard message when launching the app
  src/core/clipboardmanager.cpp
  src/core/clipboardmanager.h
Labels: backport release-3_6

#6285 Fix map center positioning with rotation and information drawer
  src/core/qgsquick/qgsquickmapsettings.cpp
  src/qml/geometryeditors/VertexEditor.qml
Labels: backport release-3_6

#6299 feat(localized): adapt to the latest changes in the server API and support vector files as shared datasets
  src/core/qfieldcloud/qfieldcloudproject.cpp
  src/core/qfieldcloud/qfieldcloudproject.h
  src/core/qfieldcloud/qfieldcloudprojectsmodel.cpp
Labels: backport release-3_6

#6307 Fix two additional 3.6 crashers
  src/core/attributeformmodelbase.cpp
  src/core/pluginmanager.cpp
  src/core/utils/featureutils.cpp
Labels: backport release-3_6

#6312 Fix file association while still making sure we don't crash
  platform/android/src/ch/opengis/qfield/QFieldActivity.java
Labels: backport release-3_6
