Repository opengisch/QField, pull requests merged in 2025-02, with the labels that each got.

#5993 Implement a default print layout when none available
  resources/sample_projects/bees.qgz.jpg
  resources/sample_projects/datasets/qgep_reach.gpkg
  resources/sample_projects/datasets/qgep_wastewater_structure.gpkg
  resources/sample_projects/live_qfield_users_survey.qgs.jpg
  resources/sample_projects/wastewater.qgz
  resources/sample_projects/wastewater.qgz.jpg
  resources/templates/layout.qpt
  src/core/processing/processingalgorithm.cpp
  src/core/qgismobileapp.cpp
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#5855 Rework pg_service.conf handling to support SSL keys authentication
  src/app/main.cpp
  src/core/platforms/platformutilities.cpp
  src/core/platforms/platformutilities.h
  src/core/qgismobileapp.cpp
Labels: ENHANCEMENT, backport release-3_5

#6015 Only ignore SSL errors on non qfield.cloud endpoints
  src/core/networkreply.cpp
Labels: backport release-3_5

#6012 Restore Stylus Binding to CoordinateLocator
  src/qml/qgismobileapp.qml
Labels: backport release-3_5

#6008 Center Map on Vertex Addition When Position Locked & Off-Screen
  src/qml/CoordinateLocator.qml
Labels: backport release-3_5

#6028 Silence another (harmless) warning on QField launch/exit
  src/qml/qgismobileapp.qml
Labels: backport release-3_5

#6032 Fix 3.5.0 crashes reported by Googe Play Store
  platform/android/src/ch/opengis/qfield/QFieldPositioningService.java
  src/app/CMakeLists.txt
  src/core/qgismobileapp.cpp
  src/qml/qgismobileapp.qml
  test/testdata/control_images/test_projection/expected_test_projection-Darwin.png
Labels: backport release-3_5

#6036 Disable sentry on system where it's inactive
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: backport release-3_5

#6041 fix goto locator to support leading NESW
  src/core/locator/gotolocatorfilter.cpp
Labels: Squash!, backport release-3_5
