Repository opengisch/QField, pull requests merged in 2025-07, with the labels that each got.

#6424 Explode geometry lock into 4 distinct permission locks
  src/core/featuremodel.cpp
  src/core/featuremodel.h
  src/core/layertreemodel.cpp
  src/core/layertreemodel.h
  src/core/multifeaturelistmodelbase.cpp
  src/core/utils/layerutils.cpp
  src/core/utils/layerutils.h
  src/qml/DashBoard.qml
  src/qml/FeatureForm.qml
  src/qml/LayerTreeItemProperties.qml
  src/qml/Legend.qml
  src/qml/NavigationBar.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#6427 Add Contextual Hints for Dashboard Buttons and Interactive Guide Actions
  src/qml/DashBoard.qml
  src/qml/QFieldGuide.qml
  src/qml/qgismobileapp.qml
Labels: ENHANCEMENT

#6431 Implement imported folder naming customization
  src/core/webdavconnection.cpp
  src/core/webdavconnection.h
  src/qml/QFieldLocalDataPickerScreen.qml
Labels: ENHANCEMENT

#6444 Hide rotate feature for singlepart point geometries
  src/qml/NavigationBar.qml
Labels: backport release-3_6

#6453 Fix dashboard guides re-appearing all the time during the first app launch
  src/qml/qgismobileapp.qml
Labels: backport release-3_6

#6456 Allow for plugins to add a description to search bar locator filters
  src/core/locator/activelayerfeatureslocatorfilter.h
  src/core/locator/bookmarklocatorfilter.h
  src/core/locator/expressioncalculatorlocatorfilter.h
  src/core/locator/featureslocatorfilter.h
  src/core/locator/gotolocatorfilter.h
  src/core/locator/helplocatorfilter.h
  src/core/locator/locatormodelsuperbridge.cpp
  src/core/locator/qfieldlocatorfilter.cpp
  src/core/locator/qfieldlocatorfilter.h
Labels: ENHANCEMENT

#6461 Fix altitude reporting on Android >= 15
  vcpkg/ports/qtpositioning/androidaltitude.patch
  vcpkg/ports/qtpositioning/portfile.cmake
Labels: backport release-3_6

#6455 Implement remote plugin information cache and add a "trusted" state
  src/core/pluginmanager.cpp
  src/core/pluginmanager.h
  src/core/pluginmodel.cpp
  src/core/pluginmodel.h
  src/qml/PluginItem.qml
  src/qml/PluginManagerSettings.qml
Labels: ENHANCEMENT

#6466 Fix image sketching and audio recording on Windows
  src/core/drawingcanvas.cpp
  src/core/platforms/platformutilities.cpp
  src/core/utils/urlutils.cpp
  src/core/utils/urlutils.h
  src/qml/QFieldAudioRecorder.qml
  src/qml/QFieldCamera.qml
  src/qml/QFieldSketcher.qml
  src/qml/editorwidgets/ExternalResource.qml
Labels: backport release-3_6

#6473 Implement image stamping customization functionality
  src/core/utils/fileutils.cpp
  src/core/utils/fileutils.h
  src/qml/QFieldCamera.qml
Labels: ENHANCEMENT, needs documentation

#6506 Fix type leading to auto push interval configuration not taken into account
  src/qml/qgismobileapp.qml
Labels: backport release-3_7

#6508 Fix NMEA connection logging on Android
  src/core/positioning/abstractgnssreceiver.h
  src/core/positioning/nmeagnssreceiver.cpp
  src/core/positioning/nmeagnssreceiver.h
  src/core/positioning/positioning.cpp
  src/core/positioning/positioning.h
  src/core/positioning/positioningsource.cpp
  src/core/positioning/positioningsource.h
  src/qml/qgismobileapp.qml
Labels: backport release-3_7

#6514 Skip feature form-driven map canvas margins when moving/rotating features
  src/qml/FeatureListForm.qml
  src/qml/qgismobileapp.qml
Labels: backport release-3_7
